<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="4" hostname="DESKTOP-8A1HO0F" failures="1" tests="1" name="Default test" time="9.33" errors="0" timestamp="2024-07-18T20:43:43 IST">
  <testcase classname="com.tutorialsninja.qa.testcases.Login" name="verifyLoginWithInValidCredentials" time="0.328">
    <failure type="java.lang.IllegalArgumentException" message="Keys to send should be a not null CharSequence">
      <![CDATA[java.lang.IllegalArgumentException: Keys to send should be a not null CharSequence
at org.openqa.selenium.remote.RemoteWebElement.sendKeys(RemoteWebElement.java:96)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
at java.base/java.lang.reflect.Method.invoke(Method.java:577)
at org.openqa.selenium.support.pagefactory.internal.LocatingElementHandler.invoke(LocatingElementHandler.java:51)
at jdk.proxy2/jdk.proxy2.$Proxy13.sendKeys(Unknown Source)
at com.tutorialsninja.qa.pages.LoginPage.login(LoginPage.java:35)
at com.tutorialsninja.qa.testcases.Login.verifyLoginWithInValidCredentials(Login.java:60)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
at java.base/java.lang.reflect.Method.invoke(Method.java:577)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:686)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:230)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:992)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:739)
at org.testng.TestRunner.run(TestRunner.java:614)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:413)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:373)
at org.testng.SuiteRunner.run(SuiteRunner.java:312)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1274)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1208)
at org.testng.TestNG.runSuites(TestNG.java:1112)
at org.testng.TestNG.run(TestNG.java:1079)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
    </failure>
  </testcase> <!-- verifyLoginWithInValidCredentials -->
  <testcase classname="com.tutorialsninja.qa.testcases.Login" name="verifyLoginWithoutProvidingCredentials" time="0.0">
    <ignored/>
  </testcase> <!-- verifyLoginWithoutProvidingCredentials -->
  <testcase classname="com.tutorialsninja.qa.testcases.Login" name="verifyLoginWithValidEmailAndInvalidPassword" time="0.0">
    <ignored/>
  </testcase> <!-- verifyLoginWithValidEmailAndInvalidPassword -->
  <testcase classname="com.tutorialsninja.qa.testcases.Login" name="verifyLoginWithValidCredentials" time="0.0">
    <ignored/>
  </testcase> <!-- verifyLoginWithValidCredentials -->
  <testcase classname="com.tutorialsninja.qa.testcases.Login" name="verifyLoginWithInvalidEmailAndValidPassword" time="0.0">
    <ignored/>
  </testcase> <!-- verifyLoginWithInvalidEmailAndValidPassword -->
</testsuite> <!-- Default test -->
